### ISSUE TITLE
Problems adding the datasource

### ISSUE THREAD

**Issue by kerneljack** [mtanda/grafana-google-stackdriver-datasource#5] opened 2017-11-15 17:21 UTC
Hi there,

I've created a OAuth 2.0 client ID and filled in both the "Authorised JavaScript origins" and the "Authorised redirect URIs" correctly, however, when I attempt to click "Save & Test", it just hangs and nothing happens?

Can you please help me figure out what the problem could be? I've attached a screenshot.

![screen shot 2017-11-15 at 17 20 03](https://user-images.githubusercontent.com/927623/32850210-6f420e0e-ca29-11e7-8f08-0cd47e6a9d29.png)

**Comment by mtanda** [comment] 2017-11-16 09:48
It's strange. I try to replicate, but I can't.

Any error message is shown?
And what version Grafana, and commit id of stackdriver datasource.

**Comment by kerneljack** [comment] 2017-11-16 10:31
Thanks for checking! 

`$ grafana-server -v
Version 4.5.2 (commit: ec2b0fe)`

I am running Grafana inside a Docker container, and I installed the plugin by doing a `git clone` and copying the files into `/var/lib/grafana/plugins/stackdriver`. Is that the right way to do it? I made sure everything is owned by the `grafana` user.

It just says *Datasource updated* but i don't see any other errors in the web UI. In the Javascript console, I can see the following coming back from Google:
```
Failed to load https://apis.google.com/js/api.js?bust=<bust_id>: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://grafana.<ourdomain.com>' is therefore not allowed access.

Potentially unhandled rejection [3] (SystemJS) XHR error loading https://apis.google.com/js/api.js?bust=<bust_id>
	Error: XHR error loading https://apis.google.com/js/api.js?bust=<bust_id>
	Error loading https://apis.google.com/js/api.js
```

I checked the actual logs of Grafana but I couldn't see any errors related to `stackdriver` or the datasource, do you log any errors there?

**Comment by kerneljack** [comment] 2017-11-16 14:17
What is the commit id of the Stackdriver resource? Where do I find that?

**Comment by mtanda** [comment] 2017-11-17 03:27
hmm, the datasource plugin is latest.
I met same error before, and fix it @ https://github.com/mtanda/grafana-google-stackdriver-datasource/commit/aeab45629df0b4761904a493b06961be76f68a70 .
The latest code should work...

I'll check it later.

**Comment by mtanda** [comment] 2017-11-17 03:44
Latest datasource plugin needs ace editor, I'm not sure this plugin work with Grafana 4.5.2.
This is another issue, but you may need to update Grafana.

So, please try Grafana 4.6.2, and inform me the error still happen.

**Comment by kerneljack** [comment] 2017-11-17 20:11
@mtanda thanks, I will try that and let you know!

**Comment by mtanda** [comment] 2017-12-06 04:33
@kerneljack Hi, is your problem solved?

**Comment by mtanda** [comment] 2017-12-14 06:56
Sorry, I close this issue.
Feel free to reopen, if the issue is not solved.

**Closed by mtanda** 2017-12-14 06:56 UTC

**Comment by kerneljack** [comment] 2017-12-14 10:19
Yes, I'll let you know, thanks, @mtanda :-)
